- name: Get user details from hashi vault
  hosts: all
  # become: False
  gather_facts: False
  tasks:

  - debug:
      msg: "{{ hostvars }}"
  
  - name: Update Inventory
    dynamic_inventory_info: 
      scan_network: '192.168.1.0/24'
      scan_port: 22
    delegate_to: localhost